resource_group_name       = "flowforge-prod-rg"
location                  = "East US"
admin_username            = "noeladmin"
admin_password            = "ProdEnv@124" 
pfx_certificate_path      = "./flowforge-ssl.pfx" 
pfx_certificate_password  = "flowforgessl"